### ISSUE TITLE
Incompatibility with Unity 5.5.0xb1 Linux Personal

### ISSUE THREAD

**Issue by lpinilla** [Unity-Technologies/PostProcessing#314]
##### What happened?
I imported the pack PostProcessing from Unity and couldn't find how to create a new Post-Processing Profile (doing right click/create) so I restarted the program. Then Unity opened with a Console Error:

Assets/PostProcessing/Runtime/Components/TaaComponent.cs(71,28): error CS1061: Type `UnityEngine.Camera' does not contain a definition for `useJitteredProjectionMatrixForTransparentRendering' and no extension method `useJitteredProjectionMatrixForTransparentRendering' of type `UnityEngine.Camera' could be found. Are you missing an assembly reference?

##### Post-processing stack version (v1, v2)?
v1.0.4
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
 Unity 5.5.0xb1 Linux Personal. Target: Android

**Comment by j4james** [comment]
According to the [documentation](https://github.com/Unity-Technologies/PostProcessing/wiki/(v1)-Quickstart#restrictions), the v1 postprocessing stack requires Unity 5.4.1+ or Unity 5.5.0b6+ (it won't work with previous beta versions of 5.5.0).

**Comment by Kink3d** [comment]
Hi,

As j4james has stated, this error is because that version of Unity does not support the jittered projection matrix required by Temporal Anti-aliasing. Please update your Unity version (I would definitely get out of 5.5 beta anyway I were you) to enjoy the Post-processing stack. 

Thanks

**Comment by lpinilla** [comment]
Thank you for replying. 

Guess I need to update Unity!
