### ISSUE TITLE
post effect behaviour Not working in unity 5.6.0b1

### ISSUE THREAD

**Issue by patrickd3** [Unity-Technologies/PostProcessing#44]
Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs(266,34): error CS1955: The member `UnityEngine.PostProcessing.PostProcessingProfile.MonitorSettings.onFrameEndEditorOnly' cannot be used as method or delegate

**Comment by Kink3d** [comment]
Hi,

Thanks for reporting the issue. This should be fixed in 5.6.0b3.

Regards
