### ISSUE TITLE
'MinAttribute' is an ambiguous reference between 'UnityEngine.PostProcessing.MinAttribute' and 'UnityEngine.MinAttribute'

### ISSUE THREAD

**Issue by rhys-vdw** [Unity-Technologies/PostProcessing#725]
##### What happened?

After updating to 2018.3

```
Assets/Vendor/PostProcessing/Editor/PropertyDrawers/MinDrawer.cs(6,34): error CS0104: 'MinAttribute' is an ambiguous reference between 'UnityEngine.PostProcessing.MinAttribute' and 'UnityEngine.MinAttribute'
```

##### Post-processing stack version (v1, v2)?

v1 (I think) see #724

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

2018.3 macOS

**Comment by Sjooy** [comment]
It's mixing up two identifiers. 

Change the MinDrawer.cs to this:

```
using UnityEngine;
using UnityEngine.PostProcessing;

namespace UnityEditor.PostProcessing
{
    [CustomPropertyDrawer(typeof(UnityEngine.PostProcessing.MinAttribute))]
    sealed class MinDrawer : PropertyDrawer
    {
        public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
        {
            UnityEngine.PostProcessing.MinAttribute attribute = (UnityEngine.PostProcessing.MinAttribute)base.attribute;

            if (property.propertyType == SerializedPropertyType.Integer)
            {
                int v = EditorGUI.IntField(position, label, property.intValue);
                property.intValue = (int)Mathf.Max(v, attribute.min);
            }
            else if (property.propertyType == SerializedPropertyType.Float)
            {
                float v = EditorGUI.FloatField(position, label, property.floatValue);
                property.floatValue = Mathf.Max(v, attribute.min);
            }
            else
            {
                EditorGUI.LabelField(position, label.text, "Use Min with float or int.");
            }
        }
    }
}
```

**Comment by rhys-vdw** [comment]
Thanks @Sjooy.

Actually the simpler fix is to add one line at the top:

```cs
using MinAttribute = UnityEngine.PostProcessing.MinAttribute;
```

I opened this issue to alert the developers to the fact that their asset store build is broken for Unity 2018.3.

**Comment by andreujuanc** [comment]
Good! I wasnt sure which was should i be using.

**Comment by sajdude** [comment]
> 
> 
> Thanks @Sjooy.
> 
> Actually the simpler fix is to add one line at the top:
> 
> ```cs
> using MinAttribute = UnityEngine.PostProcessing.MinAttribute;
> ```
> 
> I opened this issue to alert the developers to the fact that their asset store build is broken for Unity 2018.3.

Thank you,

**Comment by salexmatei** [comment]
actually it seems to be using MinAttribute = UnityEngine.Rendering.PostProcessing.MinAttribute;

**Comment by Koekoek2006** [comment]
> Thanks @Sjooy.
> 
> Actually the simpler fix is to add one line at the top:
> 
> ```cs
> using MinAttribute = UnityEngine.PostProcessing.MinAttribute;
> ```
> 
> I opened this issue to alert the developers to the fact that their asset store build is broken for Unity 2018.3.

When I do this I get the errors 
```
Assets\Environment\PostProcessing\Editor\Utils\CurveEditor.cs(379,35): error CS0619: 'EventType.repaint' is obsolete: 'Use Repaint instead (UnityUpgradable) -> Repaint'
Assets\Environment\PostProcessing\Editor\Utils\CurveEditor.cs(425,35): error CS0619: 'EventType.mouseDown' is obsolete: 'Use MouseDown instead (UnityUpgradable) -> MouseDown'
Assets\Environment\PostProcessing\Editor\Utils\CurveEditor.cs(456,35): error CS0619: 'EventType.mouseDown' is obsolete: 'Use MouseDown instead (UnityUpgradable) -> MouseDown'
Assets\Environment\PostProcessing\Editor\Utils\CurveEditor.cs(502,27): error CS0619: 'EventType.mouseDown' is obsolete: 'Use MouseDown instead (UnityUpgradable) -> MouseDown'
Assets\Environment\PostProcessing\Editor\Utils\CurveEditor.cs(585,27): error CS0619: 'EventType.keyDown' is obsolete: 'Use KeyDown instead (UnityUpgradable) -> KeyDown'
```

How do I fix these?

**Comment by pablodefou** [comment]
> Thanks @Sjooy.
> 
> Actually the simpler fix is to add one line at the top:
> 
> ```cs
> using MinAttribute = UnityEngine.PostProcessing.MinAttribute;
> ```
> 
> I opened this issue to alert the developers to the fact that their asset store build is broken for Unity 2018.3.

Thanks mate, its works perfectly.

**Comment by Eelcapitan** [comment]
Thanks a lot... That helped..

**Comment by paulgnz** [comment]
> Thanks @Sjooy.
> 
> Actually the simpler fix is to add one line at the top:
> 
> ```cs
> using MinAttribute = UnityEngine.PostProcessing.MinAttribute;
> ```
> 
> I opened this issue to alert the developers to the fact that their asset store build is broken for Unity 2018.3.

Thanks! Confirmed working in 2018.3.11f1

**Comment by Vadyy** [comment]
Also working in 2019.1.0f2
Why is this not fixed automatically? Isn't Post Processing a default package of Unity?

**Comment by rhys-vdw** [comment]
@Vadyy it's in the package manager, but this error exists in the version on the asset store. AFAIK it's not a "default package" (assuming this means a package you can check when you install), but it may be.

**Comment by rhys-vdw** [comment]
@Vadyy to be more specific: The asset store version cannot be updated or deprecated, hence the package manager. The problem here is that both Unity itself and this package are adding symbols to the global namespace, which is inadvisable because it can cause issues like this. If possible you'd be wise to move to the newer version via package manager.

**Comment by HelenaCrispin** [comment]
Thank you!

**Comment by Dr-WeiZhou** [comment]
I tried this proposed way to correct the error appeared in the latest version 2019.3.0a2 of Unity and it triggered serires of problems listed below:
![image](https://user-images.githubusercontent.com/38851350/58390010-86026e00-8061-11e9-91be-f206a6444606.png)

Any ideas how to cope with these? Sorry for my questions as a starter here. I tried this tutorials before and it was running correctly. But now it becomes like this. Much appreciated about kind solutions to guide me move forward. Thanks.

**Comment by Dr-WeiZhou** [comment]
I just found my own solution for the above issue and append it here: simply uninstall the latest version and reinstall the old version of Unity 2017.2.4p1 (64-bit), then the tutorial can run as normal

**Comment by betomaluje** [comment]
> I tried this proposed way to correct the error appeared in the latest version 2019.3.0a2 of Unity and it triggered serires of problems listed below:
> ![image](https://user-images.githubusercontent.com/38851350/58390010-86026e00-8061-11e9-91be-f206a6444606.png)
> 
> Any ideas how to cope with these? Sorry for my questions as a starter here. I tried several tutorials before to run correctly. But now they report many errors like this. Much appreciated about kind solutions to guide me move forward. Thanks.

I got the same error in the same version of Unity. I had to go to **Assets -> Reimport All** to fix it. Make sure to make a backup before

**Comment by Jeffreyveggie** [comment]
Auto Repratur von Visual Basic 2019 can help


using UnityEngine;
namespace UnityEditor.PostProcessing
{
    [CustomPropertyDrawer(typeof(MinAttribute))]
    sealed class MinDrawer : PropertyDrawer
    {
        public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
        {
            MinAttribute attribute = (MinAttribute)base.attribute;

            if (property.propertyType == SerializedPropertyType.Integer)
            {
                int v = EditorGUI.IntField(position, label, property.intValue);
                property.intValue = (int)Mathf.Max(v, attribute.min);
            }
            else if (property.propertyType == SerializedPropertyType.Float)
            {
                float v = EditorGUI.FloatField(position, label, property.floatValue);
                property.floatValue = Mathf.Max(v, attribute.min);
            }
            else
            {
                EditorGUI.LabelField(position, label.text, "Use Min with float or int.");
            }
        }
    }
}

**Comment by Jeffreyveggie** [comment]
> I tried this proposed way to correct the error appeared in the latest version 2019.3.0a2 of Unity and it triggered serires of problems listed below:
> 
> Any ideas how to cope with these? Sorry for my questions as a starter here. I tried several tutorials before to run correctly. But now they report many errors like this. Much appreciated about kind solutions to guide me move forward. Thanks.
> 
> I got the same error in the same version of Unity. I had to go to Assets -> Reimport All to fix it. Make sure to make a backup before


token is DRM fake...

**Comment by anmolshelke** [comment]
Creating multiple error after solving tht error , version 2019.1.0f2.

**Comment by khanwt** [comment]
Thank you guys for saving the day!
